---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
library('tidyverse')
library('lubridate')
```
```{r}
data <- read_csv('activity.csv')
#Transform the date into an appropriate format
data$date <- ymd(data$date)
```
## What is mean total number of steps taken per day?
```{r}
data %>% group_by(date) %>% summarise_at('steps', sum, na.rm = T) -> total_steps_per_day


hist(total_steps_per_day$steps, main ='Histogram of total number of steps per day', xlab = 'Total number of steps per day')

mean(total_steps_per_day$steps)
median(total_steps_per_day$steps)

```


## What is the average daily activity pattern?

```{r}
data %>% group_by(interval) %>% summarise_at('steps', mean, na.rm = T) -> average_by_time

p <- ggplot(average_by_time, aes(x = interval, y = steps))
p + geom_line() + xlab('5-minute time interval') + ylab('Average number of steps')

max_steps <-max(average_by_time$steps)
average_by_time[which(average_by_time$steps == max_steps),]
```


## Imputing missing values

```{r}
sum(is.na(data$steps))

input_data <-merge(data, average_by_time, by = 'interval', all.y = T)
input_data[is.na(input_data$steps.x),]$steps.x <- input_data[is.na(input_data$steps.x),]$steps.y
input_data <- select(input_data, -steps.y)
colnames(input_data)[2] <- 'steps'

input_data %>% group_by(date) %>% summarise_at('steps', sum, na.rm = T) -> input_total_steps_per_day


hist(input_total_steps_per_day$steps, main ='Histogram of total number of steps per day', xlab = 'Total number of steps per day')

mean(input_total_steps_per_day$steps)
median(input_total_steps_per_day$steps)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
input_data$weekday <- wday(input_data$date, label = T)
input_data$weekend <- ifelse(input_data$weekday == 'Sat' | input_data$weekday == 'Sun','weekend','weekday')


input_data %>% group_by(interval, weekend) %>% summarise_at('steps', mean, na.rm = T) -> average_by_weekend

p <- ggplot(average_by_weekend, aes(x = interval, y = steps))
p + geom_line() + xlab('5-minute time interval') + ylab('Average number of steps') + facet_wrap(~weekend)
```